baseURL = 'https://example.org/'
locale = 'es-cr'
title = 'Lupita'
theme = 'main'
removePathAccents = true

[module.hugoVersion]
  min = '0.158.0'

[taxonomies]
  category = 'category'
  topic = 'topics'

[pagination]
  pagerSize = 50

[[menus.main]]
  identifier = 'search'
  name = 'Buscar'
  pageRef = '/buscar'
  weight = 40

[[menus.footer]]
  name = 'Acerca de'
  pageRef = '/about'
  weight = 10

[[menus.footer]]
  name = 'Categorías'
  pageRef = '/category'
  weight = 20

[[menus.footer]]
  name = 'Temas'
  pageRef = '/topics'
  weight = 30
